# Generated by Django 5.1.5 on 2025-02-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_game_ranks_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.rank'),
        ),
    ]
