# Generated by Django 5.1.5 on 2025-02-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['rank_order']},
        ),
        migrations.AddField(
            model_name='rank',
            name='rank_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
